'use strict';

// Generated by fetch-backdrops-2000-2024.mjs.
const filmBackdrops={
  1:'assets/backdrops/prototype/lotr.jpg',
  3:'assets/backdrops/prototype/spirited-away.jpg',
  5:'assets/backdrops/prototype/dark-knight.jpg',
  28:'assets/backdrops/prototype/parasite.jpg',
};

const ghostBackdrops={
  'WALL-E':'assets/backdrops/prototype/wall-e.jpg',
};
